#!/bin/sh

if [ $# -eq 0 ]; then
    tag='latest'
  else
    tag=$1
fi

docker buildx build \
	--push \
	--platform \
		linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
	--tag tigersmile/memcached:$tag .


docker buildx build \
	--push \
	--platform \
		linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
	--build-arg ENABLETLS=true \
	--tag tigersmile/memcachedtls:$tag .
